[tool.poetry]
name = "startstop"
version = "0.1.0"
description = "Tiny process manager written in Python"
authors = ["Yuri Escalianti <yuriescl@gmail.com>"]
license = "MIT License"
homepage = "https://github.com/yuriescl/startstop-python"
packages = [
    { include = "startstop.py" }
]

[tool.poetry.scripts]
startstop = 'startstop:main'

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"
Cython = "^0.29.28"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
